/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Department service. Represents a row in the &quot;Contact_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.contact.model.impl.DepartmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.contact.model.impl.DepartmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @generated
 */
@ProviderType
public interface DepartmentModel extends BaseModel<Department>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this department.
	 *
	 * @return the uuid of this department
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this department.
	 *
	 * @param uuid the uuid of this department
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the group ID of this department.
	 *
	 * @return the group ID of this department
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this department.
	 *
	 * @param groupId the group ID of this department
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this department.
	 *
	 * @return the company ID of this department
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this department.
	 *
	 * @param companyId the company ID of this department
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this department.
	 *
	 * @return the user ID of this department
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this department.
	 *
	 * @param userId the user ID of this department
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this department.
	 *
	 * @return the user uuid of this department
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this department.
	 *
	 * @param userUuid the user uuid of this department
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this department.
	 *
	 * @return the user name of this department
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this department.
	 *
	 * @param userName the user name of this department
	 */
	public void setUserName(String userName);

	/**
	 * Returns the dpt ID of this department.
	 *
	 * @return the dpt ID of this department
	 */
	public long getDptId();

	/**
	 * Sets the dpt ID of this department.
	 *
	 * @param dptId the dpt ID of this department
	 */
	public void setDptId(long dptId);

	/**
	 * Returns the dpt name of this department.
	 *
	 * @return the dpt name of this department
	 */
	@AutoEscape
	public String getDptName();

	/**
	 * Sets the dpt name of this department.
	 *
	 * @param dptName the dpt name of this department
	 */
	public void setDptName(String dptName);

	/**
	 * Returns the dpt desc of this department.
	 *
	 * @return the dpt desc of this department
	 */
	@AutoEscape
	public String getDptDesc();

	/**
	 * Sets the dpt desc of this department.
	 *
	 * @param dptDesc the dpt desc of this department
	 */
	public void setDptDesc(String dptDesc);

	/**
	 * Returns the dpt status of this department.
	 *
	 * @return the dpt status of this department
	 */
	public long getDptStatus();

	/**
	 * Sets the dpt status of this department.
	 *
	 * @param dptStatus the dpt status of this department
	 */
	public void setDptStatus(long dptStatus);

	/**
	 * Returns the dpt delete of this department.
	 *
	 * @return the dpt delete of this department
	 */
	public long getDptDelete();

	/**
	 * Sets the dpt delete of this department.
	 *
	 * @param dptDelete the dpt delete of this department
	 */
	public void setDptDelete(long dptDelete);

	/**
	 * Returns the dptcreate date of this department.
	 *
	 * @return the dptcreate date of this department
	 */
	public Date getDptcreateDate();

	/**
	 * Sets the dptcreate date of this department.
	 *
	 * @param dptcreateDate the dptcreate date of this department
	 */
	public void setDptcreateDate(Date dptcreateDate);

	/**
	 * Returns the dptmodified date of this department.
	 *
	 * @return the dptmodified date of this department
	 */
	public Date getDptmodifiedDate();

	/**
	 * Sets the dptmodified date of this department.
	 *
	 * @param dptmodifiedDate the dptmodified date of this department
	 */
	public void setDptmodifiedDate(Date dptmodifiedDate);

}