/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Person service. Represents a row in the &quot;Contact_Person&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.contact.model.impl.PersonModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.contact.model.impl.PersonImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Person
 * @generated
 */
@ProviderType
public interface PersonModel extends BaseModel<Person>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a person model instance should use the {@link Person} interface instead.
	 */

	/**
	 * Returns the primary key of this person.
	 *
	 * @return the primary key of this person
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this person.
	 *
	 * @param primaryKey the primary key of this person
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this person.
	 *
	 * @return the uuid of this person
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this person.
	 *
	 * @param uuid the uuid of this person
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the group ID of this person.
	 *
	 * @return the group ID of this person
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this person.
	 *
	 * @param groupId the group ID of this person
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this person.
	 *
	 * @return the company ID of this person
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this person.
	 *
	 * @param companyId the company ID of this person
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this person.
	 *
	 * @return the user ID of this person
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this person.
	 *
	 * @param userId the user ID of this person
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this person.
	 *
	 * @return the user uuid of this person
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this person.
	 *
	 * @param userUuid the user uuid of this person
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this person.
	 *
	 * @return the user name of this person
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this person.
	 *
	 * @param userName the user name of this person
	 */
	public void setUserName(String userName);

	/**
	 * Returns the ps ID of this person.
	 *
	 * @return the ps ID of this person
	 */
	public long getPsId();

	/**
	 * Sets the ps ID of this person.
	 *
	 * @param psId the ps ID of this person
	 */
	public void setPsId(long psId);

	/**
	 * Returns the ps name of this person.
	 *
	 * @return the ps name of this person
	 */
	@AutoEscape
	public String getPsName();

	/**
	 * Sets the ps name of this person.
	 *
	 * @param psName the ps name of this person
	 */
	public void setPsName(String psName);

	/**
	 * Returns the ps position of this person.
	 *
	 * @return the ps position of this person
	 */
	@AutoEscape
	public String getPsPosition();

	/**
	 * Sets the ps position of this person.
	 *
	 * @param psPosition the ps position of this person
	 */
	public void setPsPosition(String psPosition);

	/**
	 * Returns the dpt ID of this person.
	 *
	 * @return the dpt ID of this person
	 */
	public long getDptId();

	/**
	 * Sets the dpt ID of this person.
	 *
	 * @param dptId the dpt ID of this person
	 */
	public void setDptId(long dptId);

	/**
	 * Returns the ps phone of this person.
	 *
	 * @return the ps phone of this person
	 */
	@AutoEscape
	public String getPsPhone();

	/**
	 * Sets the ps phone of this person.
	 *
	 * @param psPhone the ps phone of this person
	 */
	public void setPsPhone(String psPhone);

	/**
	 * Returns the ps email of this person.
	 *
	 * @return the ps email of this person
	 */
	@AutoEscape
	public String getPsEmail();

	/**
	 * Sets the ps email of this person.
	 *
	 * @param psEmail the ps email of this person
	 */
	public void setPsEmail(String psEmail);

	/**
	 * Returns the ps status of this person.
	 *
	 * @return the ps status of this person
	 */
	public long getPsStatus();

	/**
	 * Sets the ps status of this person.
	 *
	 * @param psStatus the ps status of this person
	 */
	public void setPsStatus(long psStatus);

	/**
	 * Returns the ps delete of this person.
	 *
	 * @return the ps delete of this person
	 */
	public long getPsDelete();

	/**
	 * Sets the ps delete of this person.
	 *
	 * @param psDelete the ps delete of this person
	 */
	public void setPsDelete(long psDelete);

	/**
	 * Returns the pscreate of this person.
	 *
	 * @return the pscreate of this person
	 */
	public Date getPscreate();

	/**
	 * Sets the pscreate of this person.
	 *
	 * @param pscreate the pscreate of this person
	 */
	public void setPscreate(Date pscreate);

	/**
	 * Returns the psmodified date of this person.
	 *
	 * @return the psmodified date of this person
	 */
	public Date getPsmodifiedDate();

	/**
	 * Sets the psmodified date of this person.
	 *
	 * @param psmodifiedDate the psmodified date of this person
	 */
	public void setPsmodifiedDate(Date psmodifiedDate);

}